package common

const (
    MATCH_INVITE_TEAM_DISAGREE = 1
    MATCH_INVITE_TEAM_IS_FULL = 2
    MATCH_TEAM_IS_EXIST_IN_TEAM = 3
    MATCH_TEAM_IS_NOT_EXIST = 4
    MATCH_TEAM_ROLE_IS_NOT_EXIST = 5
    MATCH_TEAM_IS_CAPTAIN = 6
    MATCH_TEAM_IS_MATCHING = 7
    MATCH_TEAM_IS_NOT_MATCHING = 8
    SELECT_MASTER_NOT_EXIST = 9
)
