// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: cs_logic.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SHeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SHeartbeatReq) Reset() {
	*x = C2SHeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SHeartbeatReq) ProtoMessage() {}

func (x *C2SHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SHeartbeatReq.ProtoReflect.Descriptor instead.
func (*C2SHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{0}
}

type S2CHeartbeatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CHeartbeatRes) Reset() {
	*x = S2CHeartbeatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CHeartbeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CHeartbeatRes) ProtoMessage() {}

func (x *S2CHeartbeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CHeartbeatRes.ProtoReflect.Descriptor instead.
func (*S2CHeartbeatRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{1}
}

type C2SVerifyConnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account     string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Accountid   uint64 `protobuf:"varint,2,opt,name=accountid,proto3" json:"accountid,omitempty"`
	Accesstoken string `protobuf:"bytes,3,opt,name=accesstoken,proto3" json:"accesstoken,omitempty"`
}

func (x *C2SVerifyConnReq) Reset() {
	*x = C2SVerifyConnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SVerifyConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SVerifyConnReq) ProtoMessage() {}

func (x *C2SVerifyConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SVerifyConnReq.ProtoReflect.Descriptor instead.
func (*C2SVerifyConnReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{2}
}

func (x *C2SVerifyConnReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *C2SVerifyConnReq) GetAccountid() uint64 {
	if x != nil {
		return x.Accountid
	}
	return 0
}

func (x *C2SVerifyConnReq) GetAccesstoken() string {
	if x != nil {
		return x.Accesstoken
	}
	return ""
}

type S2CVerifyConnFailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Accountid uint64 `protobuf:"varint,2,opt,name=accountid,proto3" json:"accountid,omitempty"`
	Errorcode uint32 `protobuf:"varint,3,opt,name=errorcode,proto3" json:"errorcode,omitempty"`
}

func (x *S2CVerifyConnFailRes) Reset() {
	*x = S2CVerifyConnFailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CVerifyConnFailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CVerifyConnFailRes) ProtoMessage() {}

func (x *S2CVerifyConnFailRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CVerifyConnFailRes.ProtoReflect.Descriptor instead.
func (*S2CVerifyConnFailRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{3}
}

func (x *S2CVerifyConnFailRes) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *S2CVerifyConnFailRes) GetAccountid() uint64 {
	if x != nil {
		return x.Accountid
	}
	return 0
}

func (x *S2CVerifyConnFailRes) GetErrorcode() uint32 {
	if x != nil {
		return x.Errorcode
	}
	return 0
}

type S2CGetRoleListNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Baseinfos []*RoleBaseInfo `protobuf:"bytes,1,rep,name=baseinfos,proto3" json:"baseinfos,omitempty"`
}

func (x *S2CGetRoleListNtf) Reset() {
	*x = S2CGetRoleListNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGetRoleListNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGetRoleListNtf) ProtoMessage() {}

func (x *S2CGetRoleListNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGetRoleListNtf.ProtoReflect.Descriptor instead.
func (*S2CGetRoleListNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{4}
}

func (x *S2CGetRoleListNtf) GetBaseinfos() []*RoleBaseInfo {
	if x != nil {
		return x.Baseinfos
	}
	return nil
}

type C2SCreateRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rolename string `protobuf:"bytes,1,opt,name=rolename,proto3" json:"rolename,omitempty"`
}

func (x *C2SCreateRoleReq) Reset() {
	*x = C2SCreateRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCreateRoleReq) ProtoMessage() {}

func (x *C2SCreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCreateRoleReq.ProtoReflect.Descriptor instead.
func (*C2SCreateRoleReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{5}
}

func (x *C2SCreateRoleReq) GetRolename() string {
	if x != nil {
		return x.Rolename
	}
	return ""
}

type S2CCreateRoleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errorcode uint32        `protobuf:"varint,1,opt,name=errorcode,proto3" json:"errorcode,omitempty"`
	Rolename  string        `protobuf:"bytes,2,opt,name=rolename,proto3" json:"rolename,omitempty"`
	Baseinfo  *RoleBaseInfo `protobuf:"bytes,3,opt,name=baseinfo,proto3" json:"baseinfo,omitempty"`
}

func (x *S2CCreateRoleRes) Reset() {
	*x = S2CCreateRoleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CCreateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCreateRoleRes) ProtoMessage() {}

func (x *S2CCreateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCreateRoleRes.ProtoReflect.Descriptor instead.
func (*S2CCreateRoleRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{6}
}

func (x *S2CCreateRoleRes) GetErrorcode() uint32 {
	if x != nil {
		return x.Errorcode
	}
	return 0
}

func (x *S2CCreateRoleRes) GetRolename() string {
	if x != nil {
		return x.Rolename
	}
	return ""
}

func (x *S2CCreateRoleRes) GetBaseinfo() *RoleBaseInfo {
	if x != nil {
		return x.Baseinfo
	}
	return nil
}

type C2SGameLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roleid uint64 `protobuf:"varint,1,opt,name=roleid,proto3" json:"roleid,omitempty"`
}

func (x *C2SGameLoginReq) Reset() {
	*x = C2SGameLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGameLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGameLoginReq) ProtoMessage() {}

func (x *C2SGameLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGameLoginReq.ProtoReflect.Descriptor instead.
func (*C2SGameLoginReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{7}
}

func (x *C2SGameLoginReq) GetRoleid() uint64 {
	if x != nil {
		return x.Roleid
	}
	return 0
}

type S2CGameLoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roleid       uint64        `protobuf:"varint,1,opt,name=roleid,proto3" json:"roleid,omitempty"`
	Rolename     string        `protobuf:"bytes,2,opt,name=rolename,proto3" json:"rolename,omitempty"`
	Rolelevel    uint32        `protobuf:"varint,3,opt,name=rolelevel,proto3" json:"rolelevel,omitempty"`
	Mastermodule *MasterModule `protobuf:"bytes,4,opt,name=mastermodule,proto3" json:"mastermodule,omitempty"`
}

func (x *S2CGameLoginRes) Reset() {
	*x = S2CGameLoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGameLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGameLoginRes) ProtoMessage() {}

func (x *S2CGameLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGameLoginRes.ProtoReflect.Descriptor instead.
func (*S2CGameLoginRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{8}
}

func (x *S2CGameLoginRes) GetRoleid() uint64 {
	if x != nil {
		return x.Roleid
	}
	return 0
}

func (x *S2CGameLoginRes) GetRolename() string {
	if x != nil {
		return x.Rolename
	}
	return ""
}

func (x *S2CGameLoginRes) GetRolelevel() uint32 {
	if x != nil {
		return x.Rolelevel
	}
	return 0
}

func (x *S2CGameLoginRes) GetMastermodule() *MasterModule {
	if x != nil {
		return x.Mastermodule
	}
	return nil
}

type S2CServertimeNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *S2CServertimeNtf) Reset() {
	*x = S2CServertimeNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CServertimeNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CServertimeNtf) ProtoMessage() {}

func (x *S2CServertimeNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CServertimeNtf.ProtoReflect.Descriptor instead.
func (*S2CServertimeNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{9}
}

func (x *S2CServertimeNtf) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type C2SExitGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SExitGameReq) Reset() {
	*x = C2SExitGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SExitGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SExitGameReq) ProtoMessage() {}

func (x *C2SExitGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SExitGameReq.ProtoReflect.Descriptor instead.
func (*C2SExitGameReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{10}
}

type S2CExitGameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CExitGameRes) Reset() {
	*x = S2CExitGameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CExitGameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CExitGameRes) ProtoMessage() {}

func (x *S2CExitGameRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CExitGameRes.ProtoReflect.Descriptor instead.
func (*S2CExitGameRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{11}
}

type S2CTipNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errorcode uint32   `protobuf:"varint,1,opt,name=errorcode,proto3" json:"errorcode,omitempty"`
	Paras     []string `protobuf:"bytes,2,rep,name=paras,proto3" json:"paras,omitempty"`
}

func (x *S2CTipNtf) Reset() {
	*x = S2CTipNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CTipNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CTipNtf) ProtoMessage() {}

func (x *S2CTipNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CTipNtf.ProtoReflect.Descriptor instead.
func (*S2CTipNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{12}
}

func (x *S2CTipNtf) GetErrorcode() uint32 {
	if x != nil {
		return x.Errorcode
	}
	return 0
}

func (x *S2CTipNtf) GetParas() []string {
	if x != nil {
		return x.Paras
	}
	return nil
}

//team-match
//创建房间
type C2SCreateTeamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode MatchMode `protobuf:"varint,1,opt,name=mode,proto3,enum=pb.MatchMode" json:"mode,omitempty"`
}

func (x *C2SCreateTeamReq) Reset() {
	*x = C2SCreateTeamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCreateTeamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCreateTeamReq) ProtoMessage() {}

func (x *C2SCreateTeamReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCreateTeamReq.ProtoReflect.Descriptor instead.
func (*C2SCreateTeamReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{13}
}

func (x *C2SCreateTeamReq) GetMode() MatchMode {
	if x != nil {
		return x.Mode
	}
	return MatchMode_normal_match
}

type S2CCreateTeamRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teaminfo *TeamInfo `protobuf:"bytes,1,opt,name=teaminfo,proto3" json:"teaminfo,omitempty"`
}

func (x *S2CCreateTeamRes) Reset() {
	*x = S2CCreateTeamRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CCreateTeamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCreateTeamRes) ProtoMessage() {}

func (x *S2CCreateTeamRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCreateTeamRes.ProtoReflect.Descriptor instead.
func (*S2CCreateTeamRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{14}
}

func (x *S2CCreateTeamRes) GetTeaminfo() *TeamInfo {
	if x != nil {
		return x.Teaminfo
	}
	return nil
}

//邀请好友入队
type C2SInviteTeamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode           MatchMode `protobuf:"varint,1,opt,name=mode,proto3,enum=pb.MatchMode" json:"mode,omitempty"`
	Teamid         uint64    `protobuf:"varint,2,opt,name=teamid,proto3" json:"teamid,omitempty"`
	Inviteroleid   uint64    `protobuf:"varint,3,opt,name=inviteroleid,proto3" json:"inviteroleid,omitempty"`
	Inviterolename string    `protobuf:"bytes,4,opt,name=inviterolename,proto3" json:"inviterolename,omitempty"`
}

func (x *C2SInviteTeamReq) Reset() {
	*x = C2SInviteTeamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SInviteTeamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SInviteTeamReq) ProtoMessage() {}

func (x *C2SInviteTeamReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SInviteTeamReq.ProtoReflect.Descriptor instead.
func (*C2SInviteTeamReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{15}
}

func (x *C2SInviteTeamReq) GetMode() MatchMode {
	if x != nil {
		return x.Mode
	}
	return MatchMode_normal_match
}

func (x *C2SInviteTeamReq) GetTeamid() uint64 {
	if x != nil {
		return x.Teamid
	}
	return 0
}

func (x *C2SInviteTeamReq) GetInviteroleid() uint64 {
	if x != nil {
		return x.Inviteroleid
	}
	return 0
}

func (x *C2SInviteTeamReq) GetInviterolename() string {
	if x != nil {
		return x.Inviterolename
	}
	return ""
}

type S2CInviteTeamConfirmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode   MatchMode `protobuf:"varint,1,opt,name=mode,proto3,enum=pb.MatchMode" json:"mode,omitempty"`
	Teamid uint64    `protobuf:"varint,2,opt,name=teamid,proto3" json:"teamid,omitempty"`
	RoleId uint64    `protobuf:"varint,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
}

func (x *S2CInviteTeamConfirmReq) Reset() {
	*x = S2CInviteTeamConfirmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CInviteTeamConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CInviteTeamConfirmReq) ProtoMessage() {}

func (x *S2CInviteTeamConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CInviteTeamConfirmReq.ProtoReflect.Descriptor instead.
func (*S2CInviteTeamConfirmReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{16}
}

func (x *S2CInviteTeamConfirmReq) GetMode() MatchMode {
	if x != nil {
		return x.Mode
	}
	return MatchMode_normal_match
}

func (x *S2CInviteTeamConfirmReq) GetTeamid() uint64 {
	if x != nil {
		return x.Teamid
	}
	return 0
}

func (x *S2CInviteTeamConfirmReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type C2SInviteTeamConfirmRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode    MatchMode `protobuf:"varint,1,opt,name=mode,proto3,enum=pb.MatchMode" json:"mode,omitempty"`
	Teamid  uint64    `protobuf:"varint,2,opt,name=teamid,proto3" json:"teamid,omitempty"`
	RoleId  uint64    `protobuf:"varint,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Isagree bool      `protobuf:"varint,4,opt,name=isagree,proto3" json:"isagree,omitempty"`
}

func (x *C2SInviteTeamConfirmRes) Reset() {
	*x = C2SInviteTeamConfirmRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SInviteTeamConfirmRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SInviteTeamConfirmRes) ProtoMessage() {}

func (x *C2SInviteTeamConfirmRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SInviteTeamConfirmRes.ProtoReflect.Descriptor instead.
func (*C2SInviteTeamConfirmRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{17}
}

func (x *C2SInviteTeamConfirmRes) GetMode() MatchMode {
	if x != nil {
		return x.Mode
	}
	return MatchMode_normal_match
}

func (x *C2SInviteTeamConfirmRes) GetTeamid() uint64 {
	if x != nil {
		return x.Teamid
	}
	return 0
}

func (x *C2SInviteTeamConfirmRes) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *C2SInviteTeamConfirmRes) GetIsagree() bool {
	if x != nil {
		return x.Isagree
	}
	return false
}

//被邀请人同意入队
type S2CTeamNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teaminfo *TeamInfo `protobuf:"bytes,1,opt,name=teaminfo,proto3" json:"teaminfo,omitempty"`
}

func (x *S2CTeamNtf) Reset() {
	*x = S2CTeamNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CTeamNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CTeamNtf) ProtoMessage() {}

func (x *S2CTeamNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CTeamNtf.ProtoReflect.Descriptor instead.
func (*S2CTeamNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{18}
}

func (x *S2CTeamNtf) GetTeaminfo() *TeamInfo {
	if x != nil {
		return x.Teaminfo
	}
	return nil
}

//退出队伍-返回team_ntf
type C2SLeaveTeamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode   MatchMode `protobuf:"varint,1,opt,name=mode,proto3,enum=pb.MatchMode" json:"mode,omitempty"`
	Teamid uint64    `protobuf:"varint,2,opt,name=teamid,proto3" json:"teamid,omitempty"`
}

func (x *C2SLeaveTeamReq) Reset() {
	*x = C2SLeaveTeamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLeaveTeamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLeaveTeamReq) ProtoMessage() {}

func (x *C2SLeaveTeamReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLeaveTeamReq.ProtoReflect.Descriptor instead.
func (*C2SLeaveTeamReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{19}
}

func (x *C2SLeaveTeamReq) GetMode() MatchMode {
	if x != nil {
		return x.Mode
	}
	return MatchMode_normal_match
}

func (x *C2SLeaveTeamReq) GetTeamid() uint64 {
	if x != nil {
		return x.Teamid
	}
	return 0
}

//开始匹配
type C2SStartMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SStartMatchReq) Reset() {
	*x = C2SStartMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SStartMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SStartMatchReq) ProtoMessage() {}

func (x *C2SStartMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SStartMatchReq.ProtoReflect.Descriptor instead.
func (*C2SStartMatchReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{20}
}

//取消匹配
type C2SStopMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SStopMatchReq) Reset() {
	*x = C2SStopMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SStopMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SStopMatchReq) ProtoMessage() {}

func (x *C2SStopMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SStopMatchReq.ProtoReflect.Descriptor instead.
func (*C2SStopMatchReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{21}
}

//匹配到房间确认请求
type S2CRoomConfirmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid      uint64        `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Waitmembers []*RoomMember `protobuf:"bytes,2,rep,name=waitmembers,proto3" json:"waitmembers,omitempty"`
}

func (x *S2CRoomConfirmReq) Reset() {
	*x = S2CRoomConfirmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRoomConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRoomConfirmReq) ProtoMessage() {}

func (x *S2CRoomConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRoomConfirmReq.ProtoReflect.Descriptor instead.
func (*S2CRoomConfirmReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{22}
}

func (x *S2CRoomConfirmReq) GetRoomid() uint64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *S2CRoomConfirmReq) GetWaitmembers() []*RoomMember {
	if x != nil {
		return x.Waitmembers
	}
	return nil
}

//匹配到房间确认返回
type C2SRoomConfirmRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid  uint64 `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Isagree bool   `protobuf:"varint,2,opt,name=isagree,proto3" json:"isagree,omitempty"`
}

func (x *C2SRoomConfirmRes) Reset() {
	*x = C2SRoomConfirmRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRoomConfirmRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRoomConfirmRes) ProtoMessage() {}

func (x *C2SRoomConfirmRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRoomConfirmRes.ProtoReflect.Descriptor instead.
func (*C2SRoomConfirmRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{23}
}

func (x *C2SRoomConfirmRes) GetRoomid() uint64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *C2SRoomConfirmRes) GetIsagree() bool {
	if x != nil {
		return x.Isagree
	}
	return false
}

//同意接受房间的列表通知/更换主将
type S2CRoomMemberNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*RoomMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"` //agree in room members
	Roomid  uint64        `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *S2CRoomMemberNtf) Reset() {
	*x = S2CRoomMemberNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRoomMemberNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRoomMemberNtf) ProtoMessage() {}

func (x *S2CRoomMemberNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRoomMemberNtf.ProtoReflect.Descriptor instead.
func (*S2CRoomMemberNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{24}
}

func (x *S2CRoomMemberNtf) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *S2CRoomMemberNtf) GetRoomid() uint64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

//取消匹配或者倒计时有人不接受房间,重新匹配
type S2CRestartMatchNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teaminfo *TeamInfo `protobuf:"bytes,1,opt,name=teaminfo,proto3" json:"teaminfo,omitempty"`
}

func (x *S2CRestartMatchNtf) Reset() {
	*x = S2CRestartMatchNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRestartMatchNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRestartMatchNtf) ProtoMessage() {}

func (x *S2CRestartMatchNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRestartMatchNtf.ProtoReflect.Descriptor instead.
func (*S2CRestartMatchNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{25}
}

func (x *S2CRestartMatchNtf) GetTeaminfo() *TeamInfo {
	if x != nil {
		return x.Teaminfo
	}
	return nil
}

//全部接受房间
type S2CRoomOkNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid uint64 `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *S2CRoomOkNtf) Reset() {
	*x = S2CRoomOkNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRoomOkNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRoomOkNtf) ProtoMessage() {}

func (x *S2CRoomOkNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRoomOkNtf.ProtoReflect.Descriptor instead.
func (*S2CRoomOkNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{26}
}

func (x *S2CRoomOkNtf) GetRoomid() uint64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

type C2SSelectMasterInRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterId uint32 `protobuf:"varint,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	Roomid   uint64 `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *C2SSelectMasterInRoomReq) Reset() {
	*x = C2SSelectMasterInRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SSelectMasterInRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSelectMasterInRoomReq) ProtoMessage() {}

func (x *C2SSelectMasterInRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSelectMasterInRoomReq.ProtoReflect.Descriptor instead.
func (*C2SSelectMasterInRoomReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{27}
}

func (x *C2SSelectMasterInRoomReq) GetMasterId() uint32 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *C2SSelectMasterInRoomReq) GetRoomid() uint64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

type C2SLockMasterInRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roomid uint64 `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
}

func (x *C2SLockMasterInRoomReq) Reset() {
	*x = C2SLockMasterInRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLockMasterInRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLockMasterInRoomReq) ProtoMessage() {}

func (x *C2SLockMasterInRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLockMasterInRoomReq.ProtoReflect.Descriptor instead.
func (*C2SLockMasterInRoomReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{28}
}

func (x *C2SLockMasterInRoomReq) GetRoomid() uint64 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

//战斗场景创建Ok,等待进入
type S2CSceneOkNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sceneid uint64 `protobuf:"varint,1,opt,name=sceneid,proto3" json:"sceneid,omitempty"`
	Mapid   uint32 `protobuf:"varint,2,opt,name=mapid,proto3" json:"mapid,omitempty"`
}

func (x *S2CSceneOkNtf) Reset() {
	*x = S2CSceneOkNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CSceneOkNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSceneOkNtf) ProtoMessage() {}

func (x *S2CSceneOkNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSceneOkNtf.ProtoReflect.Descriptor instead.
func (*S2CSceneOkNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{29}
}

func (x *S2CSceneOkNtf) GetSceneid() uint64 {
	if x != nil {
		return x.Sceneid
	}
	return 0
}

func (x *S2CSceneOkNtf) GetMapid() uint32 {
	if x != nil {
		return x.Mapid
	}
	return 0
}

//--------------battle----------------
type C2SBattleLoadProcessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sceneid     uint64             `protobuf:"varint,1,opt,name=sceneid,proto3" json:"sceneid,omitempty"`
	Processinfo *BattleLoadProcess `protobuf:"bytes,2,opt,name=processinfo,proto3" json:"processinfo,omitempty"`
}

func (x *C2SBattleLoadProcessReq) Reset() {
	*x = C2SBattleLoadProcessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SBattleLoadProcessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SBattleLoadProcessReq) ProtoMessage() {}

func (x *C2SBattleLoadProcessReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SBattleLoadProcessReq.ProtoReflect.Descriptor instead.
func (*C2SBattleLoadProcessReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{30}
}

func (x *C2SBattleLoadProcessReq) GetSceneid() uint64 {
	if x != nil {
		return x.Sceneid
	}
	return 0
}

func (x *C2SBattleLoadProcessReq) GetProcessinfo() *BattleLoadProcess {
	if x != nil {
		return x.Processinfo
	}
	return nil
}

type S2CBattleLoadProcessNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sceneid      uint64               `protobuf:"varint,1,opt,name=sceneid,proto3" json:"sceneid,omitempty"`
	Processinfos []*BattleLoadProcess `protobuf:"bytes,2,rep,name=processinfos,proto3" json:"processinfos,omitempty"`
}

func (x *S2CBattleLoadProcessNtf) Reset() {
	*x = S2CBattleLoadProcessNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CBattleLoadProcessNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CBattleLoadProcessNtf) ProtoMessage() {}

func (x *S2CBattleLoadProcessNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CBattleLoadProcessNtf.ProtoReflect.Descriptor instead.
func (*S2CBattleLoadProcessNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{31}
}

func (x *S2CBattleLoadProcessNtf) GetSceneid() uint64 {
	if x != nil {
		return x.Sceneid
	}
	return 0
}

func (x *S2CBattleLoadProcessNtf) GetProcessinfos() []*BattleLoadProcess {
	if x != nil {
		return x.Processinfos
	}
	return nil
}

type S2CSceneBattleMemberNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sceneid uint64 `protobuf:"varint,1,opt,name=sceneid,proto3" json:"sceneid,omitempty"`
}

func (x *S2CSceneBattleMemberNtf) Reset() {
	*x = S2CSceneBattleMemberNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CSceneBattleMemberNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSceneBattleMemberNtf) ProtoMessage() {}

func (x *S2CSceneBattleMemberNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSceneBattleMemberNtf.ProtoReflect.Descriptor instead.
func (*S2CSceneBattleMemberNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{32}
}

func (x *S2CSceneBattleMemberNtf) GetSceneid() uint64 {
	if x != nil {
		return x.Sceneid
	}
	return 0
}

//刷新棋子
type C2SRefreshChessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshMod uint32 `protobuf:"varint,1,opt,name=refresh_mod,json=refreshMod,proto3" json:"refresh_mod,omitempty"`
}

func (x *C2SRefreshChessReq) Reset() {
	*x = C2SRefreshChessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SRefreshChessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SRefreshChessReq) ProtoMessage() {}

func (x *C2SRefreshChessReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SRefreshChessReq.ProtoReflect.Descriptor instead.
func (*C2SRefreshChessReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{33}
}

func (x *C2SRefreshChessReq) GetRefreshMod() uint32 {
	if x != nil {
		return x.RefreshMod
	}
	return 0
}

type S2CRefreshChessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chesses []*ChessInfo `protobuf:"bytes,1,rep,name=chesses,proto3" json:"chesses,omitempty"`
}

func (x *S2CRefreshChessRes) Reset() {
	*x = S2CRefreshChessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CRefreshChessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CRefreshChessRes) ProtoMessage() {}

func (x *S2CRefreshChessRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CRefreshChessRes.ProtoReflect.Descriptor instead.
func (*S2CRefreshChessRes) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{34}
}

func (x *S2CRefreshChessRes) GetChesses() []*ChessInfo {
	if x != nil {
		return x.Chesses
	}
	return nil
}

//购买棋子
type C2SBuyChessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *C2SBuyChessReq) Reset() {
	*x = C2SBuyChessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SBuyChessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SBuyChessReq) ProtoMessage() {}

func (x *C2SBuyChessReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SBuyChessReq.ProtoReflect.Descriptor instead.
func (*C2SBuyChessReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{35}
}

func (x *C2SBuyChessReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type S2CWaitRegionChessNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chesses []*ChessInfo `protobuf:"bytes,1,rep,name=chesses,proto3" json:"chesses,omitempty"`
}

func (x *S2CWaitRegionChessNtf) Reset() {
	*x = S2CWaitRegionChessNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CWaitRegionChessNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWaitRegionChessNtf) ProtoMessage() {}

func (x *S2CWaitRegionChessNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWaitRegionChessNtf.ProtoReflect.Descriptor instead.
func (*S2CWaitRegionChessNtf) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{36}
}

func (x *S2CWaitRegionChessNtf) GetChesses() []*ChessInfo {
	if x != nil {
		return x.Chesses
	}
	return nil
}

//出战棋子
type C2SSelectBattleChessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *C2SSelectBattleChessReq) Reset() {
	*x = C2SSelectBattleChessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SSelectBattleChessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSelectBattleChessReq) ProtoMessage() {}

func (x *C2SSelectBattleChessReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSelectBattleChessReq.ProtoReflect.Descriptor instead.
func (*C2SSelectBattleChessReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{37}
}

func (x *C2SSelectBattleChessReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

//卖棋子
type C2SSellChessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *C2SSellChessReq) Reset() {
	*x = C2SSellChessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_logic_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SSellChessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SSellChessReq) ProtoMessage() {}

func (x *C2SSellChessReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_logic_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SSellChessReq.ProtoReflect.Descriptor instead.
func (*C2SSellChessReq) Descriptor() ([]byte, []int) {
	return file_cs_logic_proto_rawDescGZIP(), []int{38}
}

func (x *C2SSellChessReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_cs_logic_proto protoreflect.FileDescriptor

var file_cs_logic_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x63, 0x32, 0x73, 0x5f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x73, 0x32, 0x63, 0x5f, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x22, 0x6f, 0x0a, 0x13,
	0x63, 0x32, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x5f,
	0x72, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x70, 0x0a,
	0x18, 0x73, 0x32, 0x63, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x6e,
	0x5f, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x49, 0x0a, 0x15, 0x73, 0x32, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x74, 0x66, 0x12, 0x30, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x62, 0x61, 0x73, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x31, 0x0a, 0x13, 0x63, 0x32,
	0x73, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x72, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7f, 0x0a,
	0x13, 0x73, 0x32, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e,
	0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x2c,
	0x0a, 0x12, 0x63, 0x32, 0x73, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x72, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x22, 0x9d, 0x01, 0x0a,
	0x12, 0x73, 0x32, 0x63, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f,
	0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x6f, 0x6c, 0x65,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x35, 0x0a, 0x0c, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x0c,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x28, 0x0a, 0x12,
	0x73, 0x32, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6e,
	0x74, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x63, 0x32, 0x73, 0x5f, 0x65, 0x78,
	0x69, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x73,
	0x32, 0x63, 0x5f, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x22, 0x41, 0x0a, 0x0b, 0x73, 0x32, 0x63, 0x5f, 0x74, 0x69, 0x70, 0x5f, 0x6e, 0x74, 0x66, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x72, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61,
	0x72, 0x61, 0x73, 0x22, 0x39, 0x0a, 0x13, 0x63, 0x32, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x40,
	0x0a, 0x13, 0x73, 0x32, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x66, 0x6f,
	0x22, 0x9d, 0x01, 0x0a, 0x13, 0x63, 0x32, 0x73, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f,
	0x74, 0x65, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x65,
	0x61, 0x6d, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x6f,
	0x6c, 0x65, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x71, 0x0a, 0x1b, 0x73, 0x32, 0x63, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x74,
	0x65, 0x61, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x12,
	0x22, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c,
	0x65, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x1b, 0x63, 0x32, 0x73, 0x5f, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f,
	0x72, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x61, 0x67, 0x72,
	0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x61, 0x67, 0x72, 0x65,
	0x65, 0x22, 0x39, 0x0a, 0x0c, 0x73, 0x32, 0x63, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6e, 0x74,
	0x66, 0x12, 0x29, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x50, 0x0a, 0x12,
	0x63, 0x32, 0x73, 0x5f, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x72,
	0x65, 0x71, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x22, 0x15,
	0x0a, 0x13, 0x63, 0x32, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x72, 0x65, 0x71, 0x22, 0x14, 0x0a, 0x12, 0x63, 0x32, 0x73, 0x5f, 0x73, 0x74, 0x6f,
	0x70, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x22, 0x61, 0x0a, 0x14, 0x73,
	0x32, 0x63, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f,
	0x72, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x0b, 0x77,
	0x61, 0x69, 0x74, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x0b, 0x77, 0x61, 0x69, 0x74, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x48,
	0x0a, 0x14, 0x63, 0x32, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x73, 0x61, 0x67, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x69, 0x73, 0x61, 0x67, 0x72, 0x65, 0x65, 0x22, 0x58, 0x0a, 0x13, 0x73, 0x32, 0x63, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6e, 0x74, 0x66, 0x12,
	0x29, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x69, 0x64, 0x22, 0x42, 0x0a, 0x15, 0x73, 0x32, 0x63, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6e, 0x74, 0x66, 0x12, 0x29, 0x0a, 0x08, 0x74,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x65,
	0x61, 0x6d, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x29, 0x0a, 0x0f, 0x73, 0x32, 0x63, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x6f, 0x6b, 0x5f, 0x6e, 0x74, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x64, 0x22, 0x54, 0x0a, 0x1d, 0x63, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x5f,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72,
	0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x1b, 0x63, 0x32, 0x73, 0x5f, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x42,
	0x0a, 0x10, 0x73, 0x32, 0x63, 0x5f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x6f, 0x6b, 0x5f, 0x6e,
	0x74, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x61, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70,
	0x69, 0x64, 0x22, 0x72, 0x0a, 0x1b, 0x63, 0x32, 0x73, 0x5f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0b, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x74, 0x0a, 0x1b, 0x73, 0x32, 0x63, 0x5f, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x6e, 0x74, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x69, 0x64, 0x12,
	0x3b, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x0c,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x37, 0x0a, 0x1b,
	0x73, 0x32, 0x63, 0x5f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6e, 0x74, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x15, 0x63, 0x32, 0x73, 0x5f, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4d, 0x6f, 0x64, 0x22,
	0x41, 0x0a, 0x15, 0x73, 0x32, 0x63, 0x5f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x63,
	0x68, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x63,
	0x68, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x63, 0x68, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x22, 0x25, 0x0a, 0x11, 0x63, 0x32, 0x73, 0x5f, 0x62, 0x75, 0x79, 0x5f, 0x63, 0x68,
	0x65, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x19, 0x73, 0x32, 0x63,
	0x5f, 0x77, 0x61, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x68, 0x65,
	0x73, 0x73, 0x5f, 0x6e, 0x74, 0x66, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x68, 0x65,
	0x73, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x63, 0x68, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x22, 0x2f, 0x0a, 0x1b, 0x63, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x5f, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x22, 0x26, 0x0a, 0x12, 0x63, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x68,
	0x65, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_logic_proto_rawDescOnce sync.Once
	file_cs_logic_proto_rawDescData = file_cs_logic_proto_rawDesc
)

func file_cs_logic_proto_rawDescGZIP() []byte {
	file_cs_logic_proto_rawDescOnce.Do(func() {
		file_cs_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_logic_proto_rawDescData)
	})
	return file_cs_logic_proto_rawDescData
}

var file_cs_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_cs_logic_proto_goTypes = []interface{}{
	(*C2SHeartbeatReq)(nil),          // 0: pb.c2s_heartbeat_req
	(*S2CHeartbeatRes)(nil),          // 1: pb.s2c_heartbeat_res
	(*C2SVerifyConnReq)(nil),         // 2: pb.c2s_verify_conn_req
	(*S2CVerifyConnFailRes)(nil),     // 3: pb.s2c_verify_conn_fail_res
	(*S2CGetRoleListNtf)(nil),        // 4: pb.s2c_get_role_list_ntf
	(*C2SCreateRoleReq)(nil),         // 5: pb.c2s_create_role_req
	(*S2CCreateRoleRes)(nil),         // 6: pb.s2c_create_role_res
	(*C2SGameLoginReq)(nil),          // 7: pb.c2s_game_login_req
	(*S2CGameLoginRes)(nil),          // 8: pb.s2c_game_login_res
	(*S2CServertimeNtf)(nil),         // 9: pb.s2c_servertime_ntf
	(*C2SExitGameReq)(nil),           // 10: pb.c2s_exit_game_req
	(*S2CExitGameRes)(nil),           // 11: pb.s2c_exit_game_res
	(*S2CTipNtf)(nil),                // 12: pb.s2c_tip_ntf
	(*C2SCreateTeamReq)(nil),         // 13: pb.c2s_create_team_req
	(*S2CCreateTeamRes)(nil),         // 14: pb.s2c_create_team_res
	(*C2SInviteTeamReq)(nil),         // 15: pb.c2s_invite_team_req
	(*S2CInviteTeamConfirmReq)(nil),  // 16: pb.s2c_invite_team_confirm_req
	(*C2SInviteTeamConfirmRes)(nil),  // 17: pb.c2s_invite_team_confirm_res
	(*S2CTeamNtf)(nil),               // 18: pb.s2c_team_ntf
	(*C2SLeaveTeamReq)(nil),          // 19: pb.c2s_leave_team_req
	(*C2SStartMatchReq)(nil),         // 20: pb.c2s_start_match_req
	(*C2SStopMatchReq)(nil),          // 21: pb.c2s_stop_match_req
	(*S2CRoomConfirmReq)(nil),        // 22: pb.s2c_room_confirm_req
	(*C2SRoomConfirmRes)(nil),        // 23: pb.c2s_room_confirm_res
	(*S2CRoomMemberNtf)(nil),         // 24: pb.s2c_room_member_ntf
	(*S2CRestartMatchNtf)(nil),       // 25: pb.s2c_restart_match_ntf
	(*S2CRoomOkNtf)(nil),             // 26: pb.s2c_room_ok_ntf
	(*C2SSelectMasterInRoomReq)(nil), // 27: pb.c2s_select_master_in_room_req
	(*C2SLockMasterInRoomReq)(nil),   // 28: pb.c2s_lock_master_in_room_req
	(*S2CSceneOkNtf)(nil),            // 29: pb.s2c_scene_ok_ntf
	(*C2SBattleLoadProcessReq)(nil),  // 30: pb.c2s_battle_load_process_req
	(*S2CBattleLoadProcessNtf)(nil),  // 31: pb.s2c_battle_load_process_ntf
	(*S2CSceneBattleMemberNtf)(nil),  // 32: pb.s2c_scene_battle_member_ntf
	(*C2SRefreshChessReq)(nil),       // 33: pb.c2s_refresh_chess_req
	(*S2CRefreshChessRes)(nil),       // 34: pb.s2c_refresh_chess_res
	(*C2SBuyChessReq)(nil),           // 35: pb.c2s_buy_chess_req
	(*S2CWaitRegionChessNtf)(nil),    // 36: pb.s2c_wait_region_chess_ntf
	(*C2SSelectBattleChessReq)(nil),  // 37: pb.c2s_select_battle_chess_req
	(*C2SSellChessReq)(nil),          // 38: pb.c2s_sell_chess_req
	(*RoleBaseInfo)(nil),             // 39: pb.role_base_info
	(*MasterModule)(nil),             // 40: pb.master_module
	(MatchMode)(0),                   // 41: pb.match_mode
	(*TeamInfo)(nil),                 // 42: pb.team_info
	(*RoomMember)(nil),               // 43: pb.room_member
	(*BattleLoadProcess)(nil),        // 44: pb.battle_load_process
	(*ChessInfo)(nil),                // 45: pb.chess_info
}
var file_cs_logic_proto_depIdxs = []int32{
	39, // 0: pb.s2c_get_role_list_ntf.baseinfos:type_name -> pb.role_base_info
	39, // 1: pb.s2c_create_role_res.baseinfo:type_name -> pb.role_base_info
	40, // 2: pb.s2c_game_login_res.mastermodule:type_name -> pb.master_module
	41, // 3: pb.c2s_create_team_req.mode:type_name -> pb.match_mode
	42, // 4: pb.s2c_create_team_res.teaminfo:type_name -> pb.team_info
	41, // 5: pb.c2s_invite_team_req.mode:type_name -> pb.match_mode
	41, // 6: pb.s2c_invite_team_confirm_req.mode:type_name -> pb.match_mode
	41, // 7: pb.c2s_invite_team_confirm_res.mode:type_name -> pb.match_mode
	42, // 8: pb.s2c_team_ntf.teaminfo:type_name -> pb.team_info
	41, // 9: pb.c2s_leave_team_req.mode:type_name -> pb.match_mode
	43, // 10: pb.s2c_room_confirm_req.waitmembers:type_name -> pb.room_member
	43, // 11: pb.s2c_room_member_ntf.members:type_name -> pb.room_member
	42, // 12: pb.s2c_restart_match_ntf.teaminfo:type_name -> pb.team_info
	44, // 13: pb.c2s_battle_load_process_req.processinfo:type_name -> pb.battle_load_process
	44, // 14: pb.s2c_battle_load_process_ntf.processinfos:type_name -> pb.battle_load_process
	45, // 15: pb.s2c_refresh_chess_res.chesses:type_name -> pb.chess_info
	45, // 16: pb.s2c_wait_region_chess_ntf.chesses:type_name -> pb.chess_info
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_cs_logic_proto_init() }
func file_cs_logic_proto_init() {
	if File_cs_logic_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cs_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SHeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CHeartbeatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SVerifyConnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CVerifyConnFailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGetRoleListNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCreateRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CCreateRoleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGameLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGameLoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CServertimeNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SExitGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CExitGameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CTipNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCreateTeamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CCreateTeamRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SInviteTeamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CInviteTeamConfirmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SInviteTeamConfirmRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CTeamNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLeaveTeamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SStartMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SStopMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRoomConfirmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRoomConfirmRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRoomMemberNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRestartMatchNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRoomOkNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SSelectMasterInRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLockMasterInRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CSceneOkNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SBattleLoadProcessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CBattleLoadProcessNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CSceneBattleMemberNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SRefreshChessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CRefreshChessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SBuyChessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CWaitRegionChessNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SSelectBattleChessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_logic_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SSellChessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_logic_proto_goTypes,
		DependencyIndexes: file_cs_logic_proto_depIdxs,
		MessageInfos:      file_cs_logic_proto_msgTypes,
	}.Build()
	File_cs_logic_proto = out.File
	file_cs_logic_proto_rawDesc = nil
	file_cs_logic_proto_goTypes = nil
	file_cs_logic_proto_depIdxs = nil
}
