// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: round.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoundBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Times1 int64  `protobuf:"varint,2,opt,name=Times1,proto3" json:"Times1,omitempty"`
	Times2 int64  `protobuf:"varint,3,opt,name=Times2,proto3" json:"Times2,omitempty"`
	Salary uint32 `protobuf:"varint,4,opt,name=Salary,proto3" json:"Salary,omitempty"`
}

func (x *RoundBase) Reset() {
	*x = RoundBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_round_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundBase) ProtoMessage() {}

func (x *RoundBase) ProtoReflect() protoreflect.Message {
	mi := &file_round_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundBase.ProtoReflect.Descriptor instead.
func (*RoundBase) Descriptor() ([]byte, []int) {
	return file_round_proto_rawDescGZIP(), []int{0}
}

func (x *RoundBase) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RoundBase) GetTimes1() int64 {
	if x != nil {
		return x.Times1
	}
	return 0
}

func (x *RoundBase) GetTimes2() int64 {
	if x != nil {
		return x.Times2
	}
	return 0
}

func (x *RoundBase) GetSalary() uint32 {
	if x != nil {
		return x.Salary
	}
	return 0
}

type RoundBaseCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas map[uint32]*RoundBase `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RoundBaseCfg) Reset() {
	*x = RoundBaseCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_round_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundBaseCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundBaseCfg) ProtoMessage() {}

func (x *RoundBaseCfg) ProtoReflect() protoreflect.Message {
	mi := &file_round_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundBaseCfg.ProtoReflect.Descriptor instead.
func (*RoundBaseCfg) Descriptor() ([]byte, []int) {
	return file_round_proto_rawDescGZIP(), []int{1}
}

func (x *RoundBaseCfg) GetDatas() map[uint32]*RoundBase {
	if x != nil {
		return x.Datas
	}
	return nil
}

var File_round_proto protoreflect.FileDescriptor

var file_round_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x63, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x61,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x31, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x42, 0x61, 0x73, 0x65, 0x43, 0x66, 0x67, 0x12, 0x35, 0x0a, 0x05, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x61, 0x73, 0x65, 0x43, 0x66, 0x67,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x1a, 0x4b, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_round_proto_rawDescOnce sync.Once
	file_round_proto_rawDescData = file_round_proto_rawDesc
)

func file_round_proto_rawDescGZIP() []byte {
	file_round_proto_rawDescOnce.Do(func() {
		file_round_proto_rawDescData = protoimpl.X.CompressGZIP(file_round_proto_rawDescData)
	})
	return file_round_proto_rawDescData
}

var file_round_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_round_proto_goTypes = []interface{}{
	(*RoundBase)(nil),    // 0: config.RoundBase
	(*RoundBaseCfg)(nil), // 1: config.RoundBaseCfg
	nil,                  // 2: config.RoundBaseCfg.DatasEntry
}
var file_round_proto_depIdxs = []int32{
	2, // 0: config.RoundBaseCfg.datas:type_name -> config.RoundBaseCfg.DatasEntry
	0, // 1: config.RoundBaseCfg.DatasEntry.value:type_name -> config.RoundBase
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_round_proto_init() }
func file_round_proto_init() {
	if File_round_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_round_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_round_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundBaseCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_round_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_round_proto_goTypes,
		DependencyIndexes: file_round_proto_depIdxs,
		MessageInfos:      file_round_proto_msgTypes,
	}.Build()
	File_round_proto = out.File
	file_round_proto_rawDesc = nil
	file_round_proto_goTypes = nil
	file_round_proto_depIdxs = nil
}
