// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: tip.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TipErrorcode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *TipErrorcode) Reset() {
	*x = TipErrorcode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipErrorcode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipErrorcode) ProtoMessage() {}

func (x *TipErrorcode) ProtoReflect() protoreflect.Message {
	mi := &file_tip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipErrorcode.ProtoReflect.Descriptor instead.
func (*TipErrorcode) Descriptor() ([]byte, []int) {
	return file_tip_proto_rawDescGZIP(), []int{0}
}

func (x *TipErrorcode) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TipErrorcode) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TipErrorcode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TipErrorcodeCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas map[uint32]*TipErrorcode `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TipErrorcodeCfg) Reset() {
	*x = TipErrorcodeCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipErrorcodeCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipErrorcodeCfg) ProtoMessage() {}

func (x *TipErrorcodeCfg) ProtoReflect() protoreflect.Message {
	mi := &file_tip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipErrorcodeCfg.ProtoReflect.Descriptor instead.
func (*TipErrorcodeCfg) Descriptor() ([]byte, []int) {
	return file_tip_proto_rawDescGZIP(), []int{1}
}

func (x *TipErrorcodeCfg) GetDatas() map[uint32]*TipErrorcode {
	if x != nil {
		return x.Datas
	}
	return nil
}

var File_tip_proto protoreflect.FileDescriptor

var file_tip_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x22, 0x4c, 0x0a, 0x0c, 0x54, 0x69, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x9b, 0x01, 0x0a, 0x0f, 0x54, 0x69, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f,
	0x64, 0x65, 0x43, 0x66, 0x67, 0x12, 0x38, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x54, 0x69,
	0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x43, 0x66, 0x67, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x1a,
	0x4e, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x54, 0x69, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x63, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tip_proto_rawDescOnce sync.Once
	file_tip_proto_rawDescData = file_tip_proto_rawDesc
)

func file_tip_proto_rawDescGZIP() []byte {
	file_tip_proto_rawDescOnce.Do(func() {
		file_tip_proto_rawDescData = protoimpl.X.CompressGZIP(file_tip_proto_rawDescData)
	})
	return file_tip_proto_rawDescData
}

var file_tip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tip_proto_goTypes = []interface{}{
	(*TipErrorcode)(nil),    // 0: config.TipErrorcode
	(*TipErrorcodeCfg)(nil), // 1: config.TipErrorcodeCfg
	nil,                     // 2: config.TipErrorcodeCfg.DatasEntry
}
var file_tip_proto_depIdxs = []int32{
	2, // 0: config.TipErrorcodeCfg.datas:type_name -> config.TipErrorcodeCfg.DatasEntry
	0, // 1: config.TipErrorcodeCfg.DatasEntry.value:type_name -> config.TipErrorcode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tip_proto_init() }
func file_tip_proto_init() {
	if File_tip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipErrorcode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipErrorcodeCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tip_proto_goTypes,
		DependencyIndexes: file_tip_proto_depIdxs,
		MessageInfos:      file_tip_proto_msgTypes,
	}.Build()
	File_tip_proto = out.File
	file_tip_proto_rawDesc = nil
	file_tip_proto_goTypes = nil
	file_tip_proto_depIdxs = nil
}
